---
language: ruby
# cache: bundler
rvm:
  - '2.2'
  - '2.1'
  - '2.0'
  - ruby-head
  - jruby-9.0
  - jruby-19mode
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: rbx-2
    - rvm: jruby-head
    - rvm: ruby-head
gemfile:
  - Gemfile
before_script:
  - |
    case "${TRAVIS_RUBY_VERSION}" in
      rbx*)
        gem install psych
        ;;
    esac
  - rake travis:before -t
script: rake travis
after_script:
  - rake travis:after -t
notifications:
  email:
    recipients:
      - halostatue@gmail.com
    on_success: change
    on_failure: always
sudo: false
