---
language: ruby
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - jruby-9.0.5.0
  - jruby-9.1.6.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
gemfile:
  - Gemfile
before_script:
  - rake travis:before -t
script: rake travis
after_script:
  - rake travis:after -t
notifications:
  email:
    recipients:
      - halostatue@gmail.com
    on_success: change
    on_failure: always
sudo: false
